-- Skema Sistem Informasi Akuntansi Penjualan Lsty Klinik

create table if not exists pelanggan (
  id_pelanggan bigint generated by default as identity primary key,
  nama text not null check (length(trim(nama)) > 0),
  no_hp text not null check (length(trim(no_hp)) > 0),
  alamat text not null default '',
  tanggal_daftar date not null default current_date
);

-- Pulihkan tabel lama yang sudah ada tanpa kolom kunci sesuai ERD.
do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'pelanggan' and column_name = 'id_pelanggan'
  ) then
    if exists (
      select 1 from information_schema.columns
      where table_schema = 'public' and table_name = 'pelanggan' and column_name = 'id'
    ) then
      alter table public.pelanggan rename column id to id_pelanggan;
    else
      alter table public.pelanggan
        add column id_pelanggan bigint generated by default as identity;
    end if;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.pelanggan'::regclass and contype = 'p'
  ) then
    alter table public.pelanggan
      add constraint pelanggan_pkey primary key (id_pelanggan);
  elsif not exists (
    select 1 from pg_constraint
    where conrelid = 'public.pelanggan'::regclass
      and contype in ('p', 'u')
      and conkey = array[(
        select attnum from pg_attribute
        where attrelid = 'public.pelanggan'::regclass and attname = 'id_pelanggan'
      )]::smallint[]
  ) then
    alter table public.pelanggan
      add constraint pelanggan_id_pelanggan_key unique (id_pelanggan);
  end if;
end;
$$;

alter table public.pelanggan add column if not exists nama text;
alter table public.pelanggan add column if not exists no_hp text;
alter table public.pelanggan add column if not exists alamat text;
alter table public.pelanggan add column if not exists tanggal_daftar date;

update public.pelanggan
set nama = coalesce(nullif(trim(nama), ''), 'Pelanggan ' || id_pelanggan::text),
    no_hp = coalesce(nullif(trim(no_hp), ''), 'Belum diisi'),
    alamat = coalesce(alamat, ''),
    tanggal_daftar = coalesce(tanggal_daftar, current_date);

alter table public.pelanggan alter column nama set not null;
alter table public.pelanggan alter column no_hp set default 'Belum diisi';
alter table public.pelanggan alter column no_hp set not null;
alter table public.pelanggan alter column alamat set default '';
alter table public.pelanggan alter column alamat set not null;
alter table public.pelanggan alter column tanggal_daftar set default current_date;
alter table public.pelanggan alter column tanggal_daftar set not null;

-- Pertahankan nomor telepon lama, tetapi jangan wajibkan kolom non-ERD saat insert baru.
do $$
declare
  kolom_lama record;
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'pelanggan' and column_name = 'telepon'
  ) then
    execute $sql$
      update public.pelanggan
      set no_hp = nullif(trim(telepon::text), '')
      where no_hp = 'Belum diisi' and nullif(trim(telepon::text), '') is not null
    $sql$;
  end if;

  for kolom_lama in
    select column_name
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'pelanggan'
      and is_nullable = 'NO'
      and is_identity = 'NO'
      and column_default is null
      and column_name not in ('id_pelanggan', 'nama', 'no_hp', 'alamat', 'tanggal_daftar')
  loop
    execute format('alter table public.pelanggan alter column %I drop not null', kolom_lama.column_name);
  end loop;
end;
$$;

create table if not exists item (
  id_item bigint generated by default as identity primary key,
  nama_item text not null check (length(trim(nama_item)) > 0),
  jenis text not null check (jenis in ('Produk', 'Jasa Treatment')),
  harga_jual numeric(14, 2) not null check (harga_jual >= 0),
  harga_pokok numeric(14, 2) not null default 0 check (harga_pokok >= 0),
  stok integer,
  constraint item_stok_jenis_check check (
    (jenis = 'Produk' and stok is not null and stok >= 0)
    or (jenis = 'Jasa Treatment' and stok is null and harga_pokok = 0)
  )
);

create table if not exists penjualan (
  id_penjualan bigint generated by default as identity primary key,
  id_pelanggan bigint not null references pelanggan(id_pelanggan),
  tanggal date not null default current_date,
  metode_pembayaran text not null check (metode_pembayaran in ('Tunai', 'Transfer', 'Kredit')),
  status_pembayaran text not null default 'Lunas' check (status_pembayaran in ('Lunas', 'Belum Lunas')),
  total numeric(14, 2) not null default 0 check (total >= 0)
);

create table if not exists detail_penjualan (
  id_detail bigint generated by default as identity primary key,
  id_penjualan bigint not null references penjualan(id_penjualan) on delete cascade,
  id_item bigint not null references item(id_item),
  jumlah integer not null check (jumlah > 0),
  harga_satuan numeric(14, 2) not null check (harga_satuan >= 0),
  subtotal numeric(14, 2) not null check (subtotal >= 0)
);

create index if not exists penjualan_tanggal_idx on penjualan(tanggal);
create index if not exists penjualan_pelanggan_idx on penjualan(id_pelanggan);
create index if not exists detail_penjualan_penjualan_idx on detail_penjualan(id_penjualan);
create index if not exists detail_penjualan_item_idx on detail_penjualan(id_item);

-- Satu baris laporan mewakili satu item pada detail transaksi.
create or replace view view_laporan_penjualan as
select
  p.tanggal,
  p.id_penjualan,
  pl.nama as nama_pelanggan,
  i.id_item,
  i.nama_item,
  i.jenis,
  d.jumlah,
  d.harga_satuan,
  d.subtotal,
  p.metode_pembayaran,
  p.status_pembayaran
from penjualan p
join pelanggan pl on pl.id_pelanggan = p.id_pelanggan
join detail_penjualan d on d.id_penjualan = p.id_penjualan
join item i on i.id_item = d.id_item;

-- Jurnal berpasangan: kas/piutang, pendapatan, serta HPP dan persediaan produk.
create or replace view view_jurnal_umum as
with debit_penjualan as (
  select
    p.tanggal,
    p.id_penjualan,
    case p.metode_pembayaran
      when 'Kredit' then 'Piutang Usaha'
      when 'Transfer' then 'Bank'
      else 'Kas'
    end as akun,
    p.total as nilai
  from penjualan p
), pendapatan as (
  select
    p.tanggal,
    p.id_penjualan,
    case i.jenis
      when 'Produk' then 'Pendapatan Penjualan Produk'
      else 'Pendapatan Jasa Treatment'
    end as akun,
    sum(d.subtotal) as nilai
  from penjualan p
  join detail_penjualan d on d.id_penjualan = p.id_penjualan
  join item i on i.id_item = d.id_item
  group by p.tanggal, p.id_penjualan, i.jenis
), hpp_produk as (
  select
    p.tanggal,
    p.id_penjualan,
    sum(d.jumlah * i.harga_pokok) as nilai
  from penjualan p
  join detail_penjualan d on d.id_penjualan = p.id_penjualan
  join item i on i.id_item = d.id_item
  where i.jenis = 'Produk'
  group by p.tanggal, p.id_penjualan
)
select tanggal, id_penjualan, 'Penerimaan penjualan'::text as keterangan,
       akun, nilai as debit, 0::numeric(14, 2) as kredit
from debit_penjualan
union all
select tanggal, id_penjualan, 'Pengakuan pendapatan'::text,
       akun, 0::numeric(14, 2), nilai
from pendapatan
union all
select tanggal, id_penjualan, 'Pengakuan HPP produk'::text,
       'Beban Pokok Penjualan'::text, nilai, 0::numeric(14, 2)
from hpp_produk
where nilai > 0
union all
select tanggal, id_penjualan, 'Pengurangan persediaan produk'::text,
       'Persediaan Produk'::text, 0::numeric(14, 2), nilai
from hpp_produk
where nilai > 0;

-- Membuat header, detail, total, dan mutasi stok dalam satu transaksi database.
create or replace function buat_penjualan(data_penjualan jsonb)
returns jsonb
language plpgsql
as $$
declare
  transaksi_id bigint;
  baris jsonb;
  item_terpilih item%rowtype;
  kuantitas integer;
  jumlah_total numeric(14, 2) := 0;
  nilai_baris numeric(14, 2);
  daftar_item jsonb;
begin
  if coalesce(jsonb_typeof(data_penjualan->'items'), 'null') <> 'array' then
    raise exception 'Daftar item transaksi tidak valid.';
  end if;
  if jsonb_array_length(data_penjualan->'items') = 0 then
    raise exception 'Tambahkan minimal satu item pada transaksi.';
  end if;

  insert into penjualan (id_pelanggan, tanggal, metode_pembayaran, status_pembayaran)
  values (
    (data_penjualan->>'id_pelanggan')::bigint,
    coalesce(nullif(data_penjualan->>'tanggal', '')::date, current_date),
    data_penjualan->>'metode_pembayaran',
    coalesce(data_penjualan->>'status_pembayaran', 'Lunas')
  )
  returning id_penjualan into transaksi_id;

  for baris in select value from jsonb_array_elements(data_penjualan->'items')
  loop
    kuantitas := (baris->>'jumlah')::integer;
    if kuantitas <= 0 then
      raise exception 'Jumlah item harus lebih dari nol.';
    end if;

    select * into item_terpilih
    from item
    where id_item = (baris->>'id_item')::bigint
    for update;

    if not found then
      raise exception 'Item tidak ditemukan.';
    end if;

    if item_terpilih.jenis = 'Produk' then
      update item
      set stok = stok - kuantitas
      where id_item = item_terpilih.id_item and stok >= kuantitas;
      if not found then
        raise exception 'Stok % tidak mencukupi.', item_terpilih.nama_item;
      end if;
    end if;

    nilai_baris := item_terpilih.harga_jual * kuantitas;
    insert into detail_penjualan (id_penjualan, id_item, jumlah, harga_satuan, subtotal)
    values (transaksi_id, item_terpilih.id_item, kuantitas, item_terpilih.harga_jual, nilai_baris);
    jumlah_total := jumlah_total + nilai_baris;
  end loop;

  update penjualan set total = jumlah_total where id_penjualan = transaksi_id;
  select coalesce(jsonb_agg(jsonb_build_object(
    'id_item', d.id_item, 'nama_item', i.nama_item, 'jumlah', d.jumlah,
    'harga_satuan', d.harga_satuan, 'subtotal', d.subtotal
  )), '[]'::jsonb)
  into daftar_item
  from detail_penjualan d join item i on i.id_item = d.id_item
  where d.id_penjualan = transaksi_id;

  return jsonb_build_object(
    'id_penjualan', transaksi_id,
    'total', jumlah_total,
    'items', daftar_item
  );
end;
$$;

grant execute on function buat_penjualan(jsonb) to anon, authenticated;

-- Data contoh pelanggan.
insert into pelanggan (nama, no_hp, alamat)
select contoh.nama, contoh.no_hp, contoh.alamat
from (values
  ('Alya Putri', '081234567801', 'Bandung'),
  ('Nadia Rahma', '081234567802', 'Cimahi'),
  ('Siska Maharani', '081234567803', 'Bandung')
) as contoh(nama, no_hp, alamat)
where not exists (select 1 from pelanggan p where p.nama = contoh.nama);

-- Produk dan jasa treatment contoh.
insert into item (nama_item, jenis, harga_jual, harga_pokok, stok)
select contoh.nama_item, contoh.jenis, contoh.harga_jual, contoh.harga_pokok, contoh.stok
from (values
  ('Serum Brightening', 'Produk', 185000::numeric, 95000::numeric, 35),
  ('Sunscreen SPF 50', 'Produk', 125000::numeric, 65000::numeric, 50),
  ('Facial Glow', 'Jasa Treatment', 250000::numeric, 0::numeric, null::integer),
  ('Laser Rejuvenation', 'Jasa Treatment', 650000::numeric, 0::numeric, null::integer),
  ('Peeling Treatment', 'Jasa Treatment', 350000::numeric, 0::numeric, null::integer)
) as contoh(nama_item, jenis, harga_jual, harga_pokok, stok)
where not exists (select 1 from item i where i.nama_item = contoh.nama_item);
